import { useCallback, useMemo, useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { useFocusEffect, useLocalSearchParams, useRouter } from 'expo-router';

import { Button } from '../../src/components/Button';
import { Card } from '../../src/components/Card';
import { ChoicePills } from '../../src/components/ChoicePills';
import { EmptyState } from '../../src/components/EmptyState';
import { Screen } from '../../src/components/Screen';
import { TaskListItem } from '../../src/components/TaskListItem';
import type { Goal, GoalStage, OperationLog, TaskStatus, TaskWithGoal } from '../../src/domain/types';
import { reconcileNotifications } from '../../src/notifications/service';
import { getGoal, getGoalTaskSummary, listGoalLogs, listGoalStages, setGoalStatus, softDeleteGoal } from '../../src/repositories/goals';
import { startReplanDraft } from '../../src/repositories/plans';
import { completeTask, listGoalTasks } from '../../src/repositories/tasks';
import { useAppTheme } from '../../src/theme/useAppTheme';
import { timeLabel } from '../../src/utils/dates';

type Tab = 'overview' | 'plan' | 'tasks' | 'records';

export default function GoalDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const router = useRouter(); const theme = useAppTheme();
  const [goal, setGoal] = useState<Goal | null>(null); const [tasks, setTasks] = useState<TaskWithGoal[]>([]); const [stages, setStages] = useState<GoalStage[]>([]); const [logs, setLogs] = useState<OperationLog[]>([]); const [summary, setSummary] = useState({ total: 0, completed: 0 }); const [tab, setTab] = useState<Tab>('overview'); const [taskFilter, setTaskFilter] = useState<'pending' | 'completed' | 'skipped' | 'all'>('pending'); const [expandedLog, setExpandedLog] = useState<string | null>(null);
  const load = useCallback(() => { if (!id) return; void Promise.all([getGoal(id), listGoalTasks(id), listGoalStages(id), listGoalLogs(id), getGoalTaskSummary(id)]).then(([g, t, s, l, sum]) => { setGoal(g); setTasks(t); setStages(s); setLogs(l); setSummary(sum); }); }, [id]);
  useFocusEffect(useCallback(() => { load(); }, [load]));
  const progress = summary.total ? Math.round(summary.completed / summary.total * 100) : 0;
  const pending = tasks.filter((task) => task.status === 'pending');
  const manage = () => {
    if (!goal) return;
    const buttons = [] as Array<{ text: string; style?: 'cancel' | 'destructive'; onPress?: () => void }>;
    if (goal.status === 'active') buttons.push({ text: '暂停目标', onPress: () => void changeStatus('paused') });
    if (goal.status === 'paused') buttons.push({ text: '恢复目标', onPress: () => void changeStatus('active') });
    if (['active', 'paused'].includes(goal.status)) buttons.push({ text: '重新规划', onPress: () => void replan() }, { text: '确认完成目标', onPress: () => confirmStatus('completed') }, { text: '终止目标', onPress: () => confirmStatus('terminated') });
    buttons.push({ text: '删除目标', style: 'destructive', onPress: deleteGoal }, { text: '取消', style: 'cancel' });
    Alert.alert('管理目标', '暂停不会自动后移任务；恢复后由你处理逾期任务或重新规划。', buttons);
  };
  const changeStatus = async (status: Goal['status']) => { if (!goal) return; await setGoalStatus(goal.id, status); await reconcileNotifications(); if (status === 'completed') router.push({ pathname: '/celebration', params: { goalId: goal.id, type: 'goal' } }); else load(); };
  const confirmStatus = (status: 'completed' | 'terminated') => Alert.alert(status === 'completed' ? '确认目标已经达成？' : '确认终止目标？', status === 'completed' ? `当前还有 ${pending.length} 项待完成任务，目标是否达成由你最终判断。` : '历史任务和记录会保留。', [{ text: '取消', style: 'cancel' }, { text: '确认', onPress: () => void changeStatus(status) }]);
  const deleteGoal = () => goal && Alert.alert('删除整个目标？', '目标、计划和历史会整体进入最近删除，所有通知将取消。', [{ text: '取消', style: 'cancel' }, { text: '删除', style: 'destructive', onPress: async () => { await softDeleteGoal(goal.id); await reconcileNotifications(); router.back(); } }]);
  const replan = async () => { if (!goal) return; try { await startReplanDraft(goal.id); router.push({ pathname: '/goals/plan', params: { id: goal.id } }); } catch (error) { Alert.alert('无法开始重新规划', error instanceof Error ? error.message : '请稍后重试'); } };
  const complete = async (taskId: string) => { const result = await completeTask(taskId); void reconcileNotifications(); load(); if (result.habitStageAchieved && result.goalId) router.push({ pathname: '/celebration', params: { goalId: result.goalId, type: 'habit' } }); };
  const filtered = taskFilter === 'all' ? tasks : tasks.filter((task) => task.status === taskFilter);
  return (
    <Screen title={goal?.title || '目标概况'} subtitle={goal ? `${goal.type === 'habit' ? '长期习惯' : '期限型目标'} · ${statusLabel(goal.status)}` : '正在读取…'} action={<Button title="管理" variant="ghost" onPress={manage} style={styles.headerButton} />}>
      {goal ? <>{goal.type === 'habit' && goal.habitStageAchievedAt ? <Card style={[styles.achievement, { backgroundColor: theme.colors.brandSoft }]}><Text style={[styles.sectionTitle, { color: theme.colors.text }]}>习惯阶段已达成</Text><Text style={[styles.body, { color: theme.colors.secondaryText }]}>已完成 {goal.habitCurrentCount}/{goal.habitTargetCount}，{goal.habitCelebrationSeenAt ? '请选择下一步。' : '查看鼓励并选择下一步。'}</Text><Button title={goal.habitCelebrationSeenAt ? '管理下一步' : '查看阶段成果'} onPress={() => router.push({ pathname: '/celebration', params: { goalId: goal.id, type: 'habit' } })} /></Card> : null}<Card style={styles.summaryCard}><Text style={[styles.description, { color: theme.colors.text }]}>{goal.description}</Text><View style={styles.progressRow}><Text style={[styles.meta, { color: theme.colors.secondaryText }]}>{goal.type === 'habit' ? `本阶段 ${goal.habitCurrentCount}/${goal.habitTargetCount} · 最佳 ${goal.habitBestCount}` : `当前进度 ${summary.completed}/${summary.total}`}</Text><Text style={[styles.progressText, { color: theme.colors.brandPressed }]}>{progress}%</Text></View><View style={[styles.track, { backgroundColor: theme.colors.border }]}><View style={[styles.fill, { width: `${progress}%`, backgroundColor: theme.colors.brand }]} /></View><Text style={[styles.meta, { color: theme.colors.secondaryText }]}>{goal.targetDate ? `目标日期 ${goal.targetDate}` : goal.habitCycle ? `习惯周期 ${goal.habitCycle}` : '无固定截止日期'}</Text></Card>
      <ChoicePills value={tab} onChange={setTab} choices={[{ value: 'overview', label: '概况' }, { value: 'plan', label: '计划' }, { value: 'tasks', label: '任务' }, { value: 'records', label: '记录' }]} />
      <View style={styles.content}>{tab === 'overview' ? <Overview tasks={tasks} stages={stages} logs={logs} /> : tab === 'plan' ? <PlanTab stages={stages} tasks={tasks} onTask={(task) => router.push({ pathname: '/tasks/[id]', params: { id: task.id } })} onComplete={complete} /> : tab === 'tasks' ? <><ChoicePills value={taskFilter} onChange={setTaskFilter} choices={[{ value: 'pending', label: '待完成' }, { value: 'completed', label: '已完成' }, { value: 'skipped', label: '已跳过' }, { value: 'all', label: '全部' }]} /><Button title="新增" variant="secondary" onPress={() => router.push({ pathname: '/tasks/new', params: { goalId: goal.id } })} style={styles.addTask} />{filtered.length ? <Card style={styles.taskCard}>{filtered.map((task) => <TaskListItem key={task.id} task={task} showGoal={false} onComplete={task.status === 'pending' ? () => void complete(task.id) : undefined} onPress={() => router.push({ pathname: '/tasks/[id]', params: { id: task.id } })} />)}</Card> : <EmptyState icon="✓" title="没有符合条件的任务" description="可以切换筛选条件查看其他任务。" />}</> : <RecordsTab logs={logs} expanded={expandedLog} onToggle={(logId) => setExpandedLog(expandedLog === logId ? null : logId)} />}</View>
      {goal.status === 'draft' ? <Button title="继续审核计划" onPress={() => router.push({ pathname: '/goals/plan', params: { id: goal.id } })} style={styles.continue} /> : null}</> : null}
    </Screen>
  );
}

function Overview({ tasks, stages, logs }: { tasks: TaskWithGoal[]; stages: GoalStage[]; logs: OperationLog[] }) { const theme = useAppTheme(); const next = tasks.find((task) => task.status === 'pending'); return <View style={styles.stack}><Card><Text style={[styles.sectionTitle, { color: theme.colors.text }]}>下一项任务</Text><Text style={[styles.body, { color: theme.colors.secondaryText }]}>{next ? `${timeLabel(next.startAt, next.dueAt)} · ${next.title}` : '当前没有待完成任务'}</Text></Card><Card><Text style={[styles.sectionTitle, { color: theme.colors.text }]}>当前阶段</Text><Text style={[styles.body, { color: theme.colors.secondaryText }]}>{next?.stageTitle ?? stages[0]?.title ?? '未设置阶段'}</Text></Card><Card><Text style={[styles.sectionTitle, { color: theme.colors.text }]}>最近进展</Text><Text style={[styles.body, { color: theme.colors.secondaryText }]}>{logs[0] ? `${actionLabel(logs[0].action)} · ${new Date(logs[0].createdAt).toLocaleString('zh-CN')}` : '暂无记录'}</Text></Card></View>; }
function PlanTab({ stages, tasks, onTask, onComplete }: { stages: GoalStage[]; tasks: TaskWithGoal[]; onTask: (task: TaskWithGoal) => void; onComplete: (id: string) => void }) { const theme = useAppTheme(); const groups = stages.length ? stages : [{ id: 'none', title: '未分阶段', description: '', order: 0, startDate: null, endDate: null }]; return <View style={styles.stack}>{groups.map((stage) => { const stageTasks = tasks.filter((task) => stage.id === 'none' ? !task.stageId : task.stageId === stage.id); if (!stageTasks.length) return null; const done = stageTasks.filter((task) => task.status === 'completed').length; return <Card key={stage.id}><Text style={[styles.sectionTitle, { color: theme.colors.text }]}>{stage.title}</Text><Text style={[styles.meta, { color: theme.colors.secondaryText }]}>{done}/{stageTasks.length} 已完成</Text>{stageTasks.map((task) => <TaskListItem key={task.id} task={task} showGoal={false} onComplete={task.status === 'pending' ? () => onComplete(task.id) : undefined} onPress={() => onTask(task)} />)}</Card>; })}</View>; }
function RecordsTab({ logs, expanded, onToggle }: { logs: OperationLog[]; expanded: string | null; onToggle: (id: string) => void }) { const theme = useAppTheme(); return logs.length ? <View style={styles.stack}>{logs.map((log) => <Pressable key={log.id} onPress={() => onToggle(log.id)}><Card><Text style={[styles.sectionTitle, { color: theme.colors.text }]}>{actionLabel(log.action)}</Text><Text style={[styles.meta, { color: theme.colors.secondaryText }]}>{new Date(log.createdAt).toLocaleString('zh-CN')}</Text>{expanded === log.id && log.metadata ? <Text style={[styles.body, { color: theme.colors.secondaryText }]}>{JSON.stringify(log.metadata, null, 2)}</Text> : null}</Card></Pressable>)}</View> : <EmptyState icon="记" title="暂无目标记录" description="打卡、延后和计划变更会显示在这里。" />; }
const statusLabel = (status: Goal['status']) => ({ draft: '草稿', active: '执行中', paused: '已暂停', completed: '已完成', terminated: '已终止' })[status];
const actionLabel = (action: string) => ({ created: '创建任务', completed: '完成', reopened: '取消完成', skipped: '跳过任务', rescheduled: '重新安排任务', edited: '编辑任务', deleted: '删除', restored: '恢复', plan_confirmed: '确认计划', plan_replaced: '替换计划', active: '恢复目标', paused: '暂停目标', terminated: '终止目标', habit_stage_achieved: '习惯阶段达成', habit_stage_continued: '开始下一习惯阶段' } as Record<string, string>)[action] ?? action;
const styles = StyleSheet.create({ headerButton: { minHeight: 38, paddingHorizontal: 12 }, achievement: { marginBottom: 12, gap: 10 }, summaryCard: { marginBottom: 12 }, description: { fontSize: 17, lineHeight: 24 }, progressRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 14 }, progressText: { fontSize: 17, fontWeight: '700' }, track: { height: 7, borderRadius: 4, overflow: 'hidden', marginVertical: 8 }, fill: { height: 7 }, meta: { fontSize: 13 }, content: { marginTop: 16 }, stack: { gap: 10 }, sectionTitle: { fontSize: 16, fontWeight: '600' }, body: { marginTop: 7, lineHeight: 21 }, addTask: { marginTop: 12, marginBottom: 10 }, taskCard: { paddingVertical: 2 }, continue: { marginTop: 20 } });
